### ISSUE TITLE
Setup Kanban Board for Hotel Hub FullStack Capstone Project

### ISSUE THREAD

**Issue by ProgramKingAbel** [ProgramKingAbel/hotel-hub-backend#13]
# Kanban Board Setup ⚒️ 

## Overview
![Capture](https://github.com/ProgramKingAbel/hotel-hub-backend/assets/33475814/0507a0bd-4dec-446c-b0c9-626e5c32c3f7)

## Collaborators -[5]

1.  @ProgramKingAbel 
2. @AleWaweru 
3. @Enoisong 
4. @sahlminkok 
5.  @Peter-Dumbari

**Comment by mcrd25** [comment]
Hi Team, 

Great work so far👏 
However there are some issues preventing me from giving the 👍 


## Highlights
- Great descriptions of tasks 👍 
- All tasks seem to match functional requirements of the project 👍 

## Optional suggestions
- Please ensure the total weight of tasks across both kanbans for any individual team member is not significantly different in weight from another, ie, no team member should have a difference in weight of more than or equal to five (or more than 4) when compared with any other team member. I nthis case, @Enoisong has 14 while  the highest is 19. That is a difference of >= 5.
- [OPTIONAL] Consider adding labels to your issues, it makes it easier to filter by different types and gives another added level of differentiation among tasks (front-end vs back-end etc.)
- [OPTIONAL] Ensure that you are adding realistic weight to your tasks.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  
Good luck! 🎉 



Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Hope all is well, and that my comments were helpful. 😸**

Cheers and Happy coding!👏👏👏


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
